### ISSUE TITLE
.phtml instead of .css

### ISSUE THREAD

**Issue by jpretired** [ric2016/compact_themes_adjuster#2]
Just an unobtrusive question:
What is the reason for using .phtml file extension instead of .css one - see theme.phtml?
Thanks, Josef

**Comment by ric2016** [comment]
Sorry, I didn't see this until now.
In some cases, the css files have to be generated because they contain dynamic code; such as urls for icons or other images including the name of the respective custom module.
This is currently not actually required here (there are no additional icons), so we could just as well use .css files directly.
