### ISSUE TITLE
Key-value pairs of the name parts - not inline again

### ISSUE THREAD

**Issue by jpretired** [ric2016/compact_themes_adjuster#5]
With webtrees-2.0.2-dev and compact_themes_adjuster-2.0.1.1 the issue is back:
![names-2 0 2-dev](https://user-images.githubusercontent.com/350656/71906882-45c4ab80-316b-11ea-9931-5a16569a0988.jpg)

Whereas with webtrees-2.0.1 it was OK:

![names-2 0 1](https://user-images.githubusercontent.com/350656/71906981-6ab91e80-316b-11ea-9296-250364417831.jpg)

Best regards, Josef

**Comment by dbq-andersons** [comment]
I just noticed this as I was integrating Rob's new theme enhancements module.  Possibly because Greg and company changed the mainline webtrees code so the names now appear inline with no modules active (neither Rob's module nor this one).

![image](https://user-images.githubusercontent.com/43183321/72158105-15555b00-337f-11ea-8523-496f8a7c4c04.png)

**Comment by jpretired** [comment]
Which lines should be deleted from theme.phtml?

**Comment by ric2016** [comment]
> Possibly because Greg and company changed the mainline webtrees code so the names now appear inline with no modules active

A (small) step in the right direction, but 'given names' still appears on two lines on large screens, because a grid layout with fixed widths is now used. I still don't quite like it and have adjusted the code (compact webtrees theme as well), the fix is not pretty (code-wise) but the names are displayed as before now.

As this only affects the dev version of webtrees, I have not released it yet - You'll have to download the respective file directly for now.
